blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/{{repo_username}}/{{repo_name}}/discussions
    about: Ask and answer questions in Discussions.
